export const data_product = [
  {
    id: 1,
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    image: "https://picsum.photos/seed/data1/600/700",
    new_price: 50.0,
    old_price: 80.5,
    category: "women",
    variants: [{ size: "M", color: "Pink", colorHex: "#EC4899", sku: "W-001", stock: 15 }],
    images: ["https://picsum.photos/seed/data1a/600/700", "https://picsum.photos/seed/data1b/600/700"],
    basePrice: 50.0,
    salePrice: 80.5,
    rating: 4.5,
    reviewsCount: 122,
    tags: ["new"],
    description: "Elegant and sophisticated blouse featuring a stunning color design.",
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    name: "Casual Linen Button-Down Shirt",
    image: "https://picsum.photos/seed/data2/600/700",
    new_price: 85.0,
    old_price: 120.5,
    category: "women",
    variants: [{ size: "G", color: "White", colorHex: "#FFFFFF", sku: "W-002", stock: 20 }],
    images: ["https://picsum.photos/seed/data2a/600/700"],
    basePrice: 85.0,
    salePrice: 120.5,
    rating: 4.0,
    reviewsCount: 88,
    tags: ["bestseller"],
    description: "Comfortable linen shirt perfect for casual days.",
    createdAt: "2024-02-10",
  },
  {
    id: 3,
    name: "Slim Fit Crop Top",
    image: "https://picsum.photos/seed/data3/600/700",
    new_price: 60.0,
    old_price: 100.5,
    category: "women",
    variants: [{ size: "P", color: "Black", colorHex: "#000000", sku: "W-003", stock: 30 }],
    images: ["https://picsum.photos/seed/data3a/600/700"],
    basePrice: 60.0,
    salePrice: 100.5,
    rating: 4.2,
    reviewsCount: 45,
    tags: ["sale"],
    description: "Trendy crop top for a modern look.",
    createdAt: "2024-03-05",
  },
  {
    id: 4,
    name: "Floral Midi Dress",
    image: "https://picsum.photos/seed/data4/600/700",
    new_price: 100.0,
    old_price: 150.0,
    category: "women",
    variants: [{ size: "M", color: "Blue", colorHex: "#2563EB", sku: "W-004", stock: 12 }],
    images: ["https://picsum.photos/seed/data4a/600/700"],
    basePrice: 100.0,
    salePrice: 150.0,
    rating: 4.8,
    reviewsCount: 210,
    tags: ["bestseller", "new"],
    description: "Beautiful floral midi dress for any occasion.",
    createdAt: "2024-04-20",
  },
];

export default data_product;
